# Generated by Django 5.0.6 on 2025-09-30 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eixo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Eixo",
                "verbose_name_plural": "Eixos",
            },
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("setor_responsavel", models.CharField(default="PGDP", max_length=120)),
                ("descricao", models.TextField(blank=True)),
                ("publico_alvo", models.TextField(blank=True)),
                ("documentos_exigidos", models.TextField(blank=True)),
                ("procedimentos", models.TextField(blank=True)),
                ("legislacao", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                ("link_sei", models.URLField(blank=True)),
                (
                    "eixo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedimentos",
                        to="guia.eixo",
                    ),
                ),
            ],
        ),
    ]
