# Generated by Django 5.0.6 on 2025-09-30 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MacroEixo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="eixo",
            options={"ordering": ["macro__ordem", "ordem", "nome"]},
        ),
        migrations.AlterModelOptions(
            name="procedimento",
            options={"ordering": ["eixo__macro__ordem", "eixo__ordem", "titulo"]},
        ),
        migrations.RenameField(
            model_name="procedimento",
            old_name="legislacao",
            new_name="base_legal",
        ),
        migrations.RenameField(
            model_name="procedimento",
            old_name="procedimentos",
            new_name="como_solicitar",
        ),
        migrations.RenameField(
            model_name="procedimento",
            old_name="documentos_exigidos",
            new_name="documentos_necessarios",
        ),
        migrations.RenameField(
            model_name="procedimento",
            old_name="descricao",
            new_name="o_que_e",
        ),
        migrations.RenameField(
            model_name="procedimento",
            old_name="publico_alvo",
            new_name="para_quem",
        ),
        migrations.AddField(
            model_name="eixo",
            name="ordem",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="procedimento",
            name="gerencia",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="prazos",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="eixo",
            name="nome",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="setor_responsavel",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name="eixo",
            name="macro",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eixos",
                to="guia.macroeixo",
            ),
            preserve_default=False,
        ),
    ]
