# Generated by Django 5.0.6 on 2025-09-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guia", "0003_fill_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerguntaFrequente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pergunta", models.CharField(max_length=255, verbose_name="Pergunta")),
                ("resposta", models.TextField(verbose_name="Resposta")),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="guia.procedimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta frequente",
                "verbose_name_plural": "Perguntas frequentes",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
